import type { Metadata } from "next";
import Link from "next/link";

import { TelemetryPreferencesButton } from "@/components/telemetry-preferences";
import { SITE_CONTACT_EMAIL, SITE_CONTACT_MAILTO } from "@/lib/site";
import { buildStaticPageMetadata } from "@/lib/seo";

export const metadata: Metadata = buildStaticPageMetadata({
  title: "Terms & Privacy | The AI Pit",
  description:
    "Terms and privacy details for The AI Pit, including AI simulation rules, hosted OpenRouter processing, public replays, analytics consent, and service providers.",
  path: "/legal",
  index: false,
  follow: true,
});

export default function LegalPage() {
  return (
    <main className="legal-page">
      <div className="legal-shell">
        <p className="legal-eyebrow">Legal</p>
        <h1 className="legal-title">Terms &amp; privacy</h1>
        <nav className="legal-section-links" aria-label="Legal sections">
          <a href="#terms">Terms</a>
          <a href="#privacy">Privacy</a>
        </nav>
        <div className="legal-copy">
          <section id="terms" className="legal-section">
            <h2>Terms of use</h2>
            <p>
              The AI Pit is provided as-is as a non-commercial experimental parody and AI simulation project for
              entertainment, creative experimentation, and interactive debate generation. It is not a factual authority,
              advice service, or official communications channel. Hosted OpenRouter access is optional, may be limited,
              changed, suspended, or removed at any time, and may be subject to usage, safety, or abuse controls.
            </p>
            <p>
              The AI Pit is available as a general experimental project but is not directed to children under 13. If you
              are under 13, do not use the app or submit prompts, personal data, or replay content.
            </p>
            <p>
              Characters, personas, voices, and debate participants generated or configured in The AI Pit are simulated
              outputs. They are presented for roleplay and entertainment purposes only and are not intended to be real
              statements, beliefs, opinions, positions, endorsements, or factual representations of any actual person,
              fictional character, brand, organization, rights holder, or estate.
            </p>
            <p>
              You must acknowledge this simulation notice before using the site. If you do not accept that condition,
              use the leave option in the notice instead of accessing the debate studio, shared replays, or other app
              surfaces.
            </p>
            <p>
              You are responsible for the prompts, character configurations, and outputs you choose to generate, review,
              or share. Do not use the app to submit unlawful content, infringing material, confidential information,
              sensitive personal data, or anything that would abuse upstream providers or violate third-party rights.
            </p>
            <p>
              Public replay links are created from user-requested AI generations and are public to anyone with the URL.
              Shared replays contain fictionalized AI-generated speech and must only be shared as AI parody simulations,
              not as real quotes, official statements, endorsements, beliefs, or positions.
            </p>
            <p>
              OpenRouter requests are routed through The AI Pit&apos;s server-side proxy. If you provide your own
              OpenRouter API key, it is stored in this browser&apos;s localStorage so it can be reused after reloads, and
              it transits the proxy so OpenRouter can complete your request using your OpenRouter account. If you use
              hosted OpenRouter access, debate content is processed through the proxy and The AI Pit&apos;s OpenRouter
              account.
            </p>
            <p>
              Outputs are generated by third-party models and may be incorrect, offensive, biased, or incomplete. Do not
              rely on outputs as real quotes, authentic viewpoints, or official positions of any depicted or referenced
              person or character, and do not rely on outputs for legal, medical, financial, employment, compliance, or
              other high-stakes decisions without independent review.
            </p>
            <p>
              The AI Pit may block or restrict hosted access for excessive usage, attempts to evade limits, policy
              violations, or conduct that threatens service stability, cost control, or safety.
            </p>
            <p>
              To report copyright, image-rights, privacy, defamation, or other legal concerns, or to request removal of
              a public replay, email{" "}
              <a href={SITE_CONTACT_MAILTO} className="underline decoration-white/30 underline-offset-4">
                {SITE_CONTACT_EMAIL}
              </a>{" "}
              with the replay URL and the reason for the request.
            </p>
            <p>
              Questions about these terms can be sent to{" "}
              <a href={SITE_CONTACT_MAILTO} className="underline decoration-white/30 underline-offset-4">
                {SITE_CONTACT_EMAIL}
              </a>
              .
            </p>
          </section>

          <section id="privacy" className="legal-section">
            <h2>Privacy policy</h2>
            <p>
              The AI Pit is provided by the operator of this deployment. Questions about this policy should be directed
              to{" "}
              <a href={SITE_CONTACT_MAILTO} className="underline decoration-white/30 underline-offset-4">
                {SITE_CONTACT_EMAIL}
              </a>
              .
            </p>
            <p>
              The AI Pit supports two OpenRouter usage modes. If you provide your own OpenRouter API key, your key,
              prompts, character settings, and model outputs are routed through The AI Pit&apos;s server-side proxy to
              OpenRouter using your OpenRouter account. If you leave the key blank and the app offers a hosted key, that
              same debate content is processed through The AI Pit&apos;s server-side proxy and then through The AI
              Pit&apos;s OpenRouter account.
            </p>
            <p>
              Debate content is processed to generate the requested debate session. The AI Pit does not provide
              account-backed transcript storage. Personal OpenRouter API keys are stored in this browser&apos;s
              localStorage under <code>aipit.openrouter-api-key</code> so the key is available after reloads. Do not
              submit other secrets, credentials, payment data, health data, or sensitive personal data through either
              OpenRouter path.
            </p>
            <p>
              If you create a public replay link, the app stores the debate prompt, character configuration, generated
              output, and related replay data needed to display that replay. Public replay links are accessible to
              anyone with the URL and contain user-requested, fictionalized AI-generated speech.
            </p>
            <p>
              Before using the site, visitors must acknowledge that portrayed characters are AI simulations and do not
              represent real opinions, beliefs, endorsements, positions, or statements of the people or entities they
              may resemble. That acknowledgement is stored only in this browser&apos;s localStorage under{" "}
              <code>aipit.simulation-acknowledgement</code> so the notice is not shown on every visit. If you choose to
              leave instead, the app redirects you away and does not store that acknowledgement.
            </p>
            <p>
              Server logs and abuse-prevention systems may temporarily process operational metadata such as request ID,
              route name, response status, timing, and IP-derived rate-limit or security signals. These records are used
              for debugging, abuse prevention, reliability, and incident response.
            </p>
            <p>
              If telemetry is configured for the deployment, visitors in European Union countries are asked for explicit
              consent before Google Analytics or client-side Sentry reporting loads. Outside the European Union,
              telemetry may load by default unless you have already declined it in this browser. Declining telemetry
              keeps the app functional and disables Google Analytics and app-level Sentry reporting where the app can
              read your preference. Hosting, security, and abuse-prevention logs may still be processed by service
              providers.
            </p>
            <p>
              Service providers may include OpenRouter for model access, Vercel or another hosting provider for serving
              the application and route handlers, Google Analytics when analytics is enabled for your browser under the
              rules above, and Sentry when app-level error reporting is enabled under your privacy preferences.
            </p>
            <p>
              This app is intended for interactive experimentation, not regulated or high-sensitivity processing. If you
              need stronger confidentiality guarantees, use your own API key or do not submit the content.
            </p>
            <p>
              To request removal of a public replay, email{" "}
              <a href={SITE_CONTACT_MAILTO} className="underline decoration-white/30 underline-offset-4">
                {SITE_CONTACT_EMAIL}
              </a>{" "}
              with the replay URL and the basis for removal, including any copyright, image-rights, privacy,
              defamation, or other legal concern.
            </p>
            <p>
              Privacy requests or questions about this policy can be sent to{" "}
              <a href={SITE_CONTACT_MAILTO} className="underline decoration-white/30 underline-offset-4">
                {SITE_CONTACT_EMAIL}
              </a>
              .
            </p>
          </section>
        </div>
        <div className="legal-actions">
          <Link href="/">Back to The AI Pit</Link>
          <TelemetryPreferencesButton />
        </div>
      </div>
    </main>
  );
}
