import type { Metadata } from "next";
import Link from "next/link";

import { SITE_CONTACT_EMAIL, SITE_CONTACT_MAILTO } from "@/lib/site";
import { buildStaticPageMetadata } from "@/lib/seo";

export const metadata: Metadata = buildStaticPageMetadata({
  title: "Terms | The AI Pit",
  description: "Terms for using The AI Pit, including the AI simulation acknowledgement and optional hosted OpenRouter access.",
  path: "/terms",
  index: false,
  follow: true,
});

export default function TermsPage() {
  return (
    <main className="legal-page">
      <div className="legal-shell">
        <p className="legal-eyebrow">Terms</p>
        <h1 className="legal-title">Terms of use</h1>
        <div className="legal-copy">
          <p>
            The AI Pit is provided as-is as a non-commercial experimental parody and AI simulation project for
            entertainment, creative experimentation, and interactive debate generation. It is not a factual authority,
            advice service, or official communications channel. Hosted OpenRouter access is optional, may be limited,
            changed, suspended, or removed at any time, and may be subject to usage, safety, or abuse controls.
          </p>
          <p>
            The AI Pit is available as a general experimental project but is not directed to children under 13. If you
            are under 13, do not use the app or submit prompts, personal data, or replay content.
          </p>
          <p>
            Characters, personas, voices, and debate participants generated or configured in The AI Pit are simulated
            outputs. They are presented for roleplay and entertainment purposes only and are not intended to be real
            statements, beliefs, opinions, positions, endorsements, or factual representations of any actual person,
            fictional character, brand, organization, rights holder, or estate.
          </p>
          <p>
            You must acknowledge this simulation notice before using the site. If you do not accept that condition, use
            the leave option in the notice instead of accessing the debate studio, shared replays, or other app
            surfaces.
          </p>
          <p>
            You are responsible for the prompts, character configurations, and outputs you choose to generate, review,
            or share. Do not use the app to submit unlawful content, infringing material, confidential information,
            sensitive personal data, or anything that would abuse upstream providers or violate third-party rights.
          </p>
          <p>
            Public replay links are created from user-requested AI generations and are public to anyone with the URL.
            Shared replays contain fictionalized AI-generated speech and must only be shared as AI parody simulations,
            not as real quotes, official statements, endorsements, beliefs, or positions.
          </p>
          <p>
            OpenRouter requests are routed through The AI Pit&apos;s server-side proxy. If you provide your own
            OpenRouter API key, that key is not intentionally persisted across reloads, but it transits the proxy so
            OpenRouter can complete your request using your OpenRouter account. If you use hosted OpenRouter access,
            debate content is processed through the proxy and The AI Pit&apos;s OpenRouter account.
          </p>
          <p>
            Outputs are generated by third-party models and may be incorrect, offensive, biased, or incomplete. Do not
            rely on outputs as real quotes, authentic viewpoints, or official positions of any depicted or referenced
            person or character, and do not rely on outputs for legal, medical, financial, employment, compliance, or
            other high-stakes decisions without independent review.
          </p>
          <p>
            The AI Pit may block or restrict hosted access for excessive usage, attempts to evade limits, policy
            violations, or conduct that threatens service stability, cost control, or safety.
          </p>
          <p>
            To report copyright, image-rights, privacy, defamation, or other legal concerns, or to request removal of a
            public replay, email{" "}
            <a href={SITE_CONTACT_MAILTO} className="underline decoration-white/30 underline-offset-4">
              {SITE_CONTACT_EMAIL}
            </a>{" "}
            with the replay URL and the reason for the request.
          </p>
          <p>
            Questions about these terms can be sent to{" "}
            <a href={SITE_CONTACT_MAILTO} className="underline decoration-white/30 underline-offset-4">
              {SITE_CONTACT_EMAIL}
            </a>
            .
          </p>
        </div>
        <div className="legal-actions">
          <Link href="/">Back to The AI Pit</Link>
        </div>
      </div>
    </main>
  );
}
