import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms | The AI Pit",
  description: "Terms for using The AI Pit and its hosted OpenRouter access.",
};

export default function TermsPage() {
  return (
    <main className="legal-page">
      <div className="legal-shell">
        <p className="legal-eyebrow">Terms</p>
        <h1 className="legal-title">Terms of use</h1>
        <div className="legal-copy">
          <p>
            The AI Pit is provided as-is for interactive debate generation. Hosted OpenRouter access may be limited,
            changed, or removed without notice.
          </p>
          <p>
            You are responsible for the prompts and character configurations you run. Do not use the app to submit
            unlawful content, abuse upstream providers, or violate third-party rights.
          </p>
          <p>
            Outputs are generated by third-party models and may be incorrect, offensive, or incomplete. Review content
            before relying on it or sharing it publicly.
          </p>
        </div>
        <div className="legal-actions">
          <Link href="/">Back to The AI Pit</Link>
        </div>
      </div>
    </main>
  );
}
